"""Model type definitions.

This module provides two types of data structures:
1. Pydantic models - For validating LLM responses with type safety
2. Plain dict factory functions - For internal pipeline data structures

Pydantic models are used when receiving data from LLMs to ensure
the response has the expected structure. Factory functions create
plain dictionaries for passing data between pipeline steps.

Why dictionaries instead of dataclasses:
- Simpler serialization to JSON for caching
- Easier to add/remove fields without class changes
- More flexible for pipeline data passing
"""

from pathlib import Path

from pydantic import BaseModel


class NarrativeSection(BaseModel):
    """Single section of a documentary narrative.

    Generated by Narrative Architect agent. Each section has:
    - title: Engaging section title for the documentary
    - objective: What this section should accomplish/cover
    - duration_seconds: Target duration for this section
    """

    title: str
    objective: str
    duration_seconds: int


class NarrativePlan(BaseModel):
    """Complete documentary plan from Narrative Architect.

    Contains the overall structure including:
    - topic: The documentary subject
    - tone: Documentary style (educational, historical, etc.)
    - pacing: How the documentary flows (steady, dynamic, etc.)
    - target_duration_seconds: Total video length target
    - sections: List of individual sections
    """

    topic: str
    tone: str
    pacing: str
    target_duration_seconds: int
    sections: list[NarrativeSection]


class VisualIntelligence(BaseModel):
    """Output from visual intelligence - search queries for images.

    Generated for each script segment to find relevant images.
    Contains optimized search queries that work well with image search APIs.
    """

    search_queries: list[str]


class ImageZone(BaseModel):
    """A zone in the script where a single image is displayed.

    Created by Image Segmentation agent. Defines:
    - zone_id: Unique identifier for this zone
    - start_sentence: First sentence this image covers
    - end_sentence: Last sentence this image covers
    - description: Brief description of what image should show
    """

    zone_id: int
    start_sentence: int
    end_sentence: int
    description: str


class ImageSegmentation(BaseModel):
    """Collection of image zones covering the entire script.

    The segmentation agent analyzes the script and determines
    where image changes should occur for optimal visual storytelling.
    """

    zones: list[ImageZone]


class SectionQuery(BaseModel):
    """A search query generated for a specific narrative section.

    Used for RAG retrieval - each section gets a query to find
    relevant research notes from the vector database.

    - section_title: Name of the narrative section
    - section_objective: What that section aims to cover
    - search_query: Optimized semantic search query
    """

    section_title: str
    section_objective: str
    search_query: str


class PlanQueries(BaseModel):
    """Collection of queries for all narrative sections.

    Generated by Query Generator agent. Contains search queries
    for retrieving relevant context for each section of the documentary.
    """

    queries: list[SectionQuery]


class ResearchNote(BaseModel):
    """A piece of research context retrieved from sources.

    - source_url: URL where this content was found
    - text: The actual content/text
    - score: Relevance score from RAG retrieval (0.0 if not applicable)
    """

    source_url: str
    text: str
    score: float = 0.0


def create_narrative_section(title, objective, duration_seconds):
    """Create a NarrativeSection dict (for internal pipeline use).

    Args:
        title: Section title
        objective: What this section covers
        duration_seconds: Target duration

    Returns:
        Dictionary with section data
    """
    return {
        "title": title,
        "objective": objective,
        "duration_seconds": duration_seconds,
    }


def create_narrative_plan(topic, tone, pacing, target_duration_seconds, sections):
    """Create a NarrativePlan dict (for internal pipeline use).

    Args:
        topic: Documentary topic
        tone: Documentary tone/style
        pacing: Pacing description
        target_duration_seconds: Total target duration
        sections: List of section dicts

    Returns:
        Dictionary with plan data
    """
    return {
        "topic": topic,
        "tone": tone,
        "pacing": pacing,
        "target_duration_seconds": target_duration_seconds,
        "sections": sections,
    }


def create_research_source(url, title, snippet=""):
    """Create a ResearchSource dict for discovered web sources.

    Args:
        url: Source URL
        title: Page title
        snippet: Optional search result snippet

    Returns:
        Dictionary with source data
    """
    result = {
        "url": url,
        "title": title,
    }
    if snippet:
        result["snippet"] = snippet
    return result


def create_research_note(source_url, text):
    """Create a ResearchNote dict from crawled content.

    Args:
        source_url: URL where content was found
        text: Extracted text content

    Returns:
        Dictionary with note data
    """
    return {
        "source_url": source_url,
        "text": text,
    }


def create_image_candidate(url, title, source, local_path=None, score=0.0):
    """Create an ImageCandidate dict for downloaded images.

    Args:
        url: Original image URL
        title: Image title/description
        source: Source website
        local_path: Path to downloaded file (if available)
        score: Ranking score (if ranked)

    Returns:
        Dictionary with candidate image data
    """
    result = {
        "url": url,
        "title": title,
        "source": source,
    }
    if local_path is not None:
        result["local_path"] = local_path
    if score != 0.0:
        result["score"] = score
    return result


def create_script_segment(
    segment_id,
    text,
    start_sentence,
    end_sentence,
    search_queries=None,
    candidate_images=None,
    selected_image_path=None,
    narration_audio_path=None,
    duration_seconds=0.0,
):
    """Create a ScriptSegment dict representing a video segment.

    A segment is a portion of the script that gets paired with a single
    image and audio clip. This is the core data structure for video assembly.

    Args:
        segment_id: Unique identifier for this segment
        text: Script text for this segment
        start_sentence: First sentence number (1-indexed)
        end_sentence: Last sentence number
        search_queries: Image search queries (optional)
        candidate_images: List of candidate images (optional)
        selected_image_path: Path to chosen image (optional)
        narration_audio_path: Path to TTS audio (optional)
        duration_seconds: Audio duration (filled in later)

    Returns:
        Dictionary with segment data
    """
    result = {
        "segment_id": segment_id,
        "text": text,
        "start_sentence": start_sentence,
        "end_sentence": end_sentence,
    }
    if search_queries is not None:
        result["search_queries"] = search_queries
    if candidate_images is not None:
        result["candidate_images"] = candidate_images
    if selected_image_path is not None:
        result["selected_image_path"] = selected_image_path
    if narration_audio_path is not None:
        result["narration_audio_path"] = narration_audio_path
    if duration_seconds != 0.0:
        result["duration_seconds"] = duration_seconds
    return result


def create_timeline_item(
    segment_id,
    text,
    start_seconds,
    end_seconds,
    duration_seconds,
    image_path,
    audio_path,
):
    """Create a TimelineItem dict for final video assembly.

    The timeline represents the complete video structure with exact
    timing for each segment.

    Args:
        segment_id: Segment identifier
        text: Script text
        start_seconds: When this segment starts
        end_seconds: When this segment ends
        duration_seconds: Duration of this segment
        image_path: Path to image file
        audio_path: Path to audio file

    Returns:
        Dictionary with timeline entry data
    """
    result = {
        "segment_id": segment_id,
        "text": text,
        "start_seconds": start_seconds,
        "end_seconds": end_seconds,
        "duration_seconds": duration_seconds,
        "image_path": image_path,
        "audio_path": audio_path,
    }
    return result


def create_research_note(source_url, text):
    """Create a ResearchNote instance."""
    return {
        "source_url": source_url,
        "text": text,
    }


def create_image_candidate(url, title, source, local_path=None, score=0.0):
    """Create an ImageCandidate instance."""
    result = {
        "url": url,
        "title": title,
        "source": source,
    }
    if local_path is not None:
        result["local_path"] = local_path
    if score != 0.0:
        result["score"] = score
    return result


def create_script_segment(
    segment_id,
    text,
    start_sentence,
    end_sentence,
    search_queries=None,
    candidate_images=None,
    selected_image_path=None,
    narration_audio_path=None,
    duration_seconds=0.0,
):
    """Create a ScriptSegment instance."""
    result = {
        "segment_id": segment_id,
        "text": text,
        "start_sentence": start_sentence,
        "end_sentence": end_sentence,
    }
    if search_queries is not None:
        result["search_queries"] = search_queries
    if candidate_images is not None:
        result["candidate_images"] = candidate_images
    if selected_image_path is not None:
        result["selected_image_path"] = selected_image_path
    if narration_audio_path is not None:
        result["narration_audio_path"] = narration_audio_path
    if duration_seconds != 0.0:
        result["duration_seconds"] = duration_seconds
    return result


def create_timeline_item(
    segment_id,
    text,
    start_seconds,
    end_seconds,
    duration_seconds,
    image_path,
    audio_path,
):
    """Create a TimelineItem instance."""
    result = {
        "segment_id": segment_id,
        "text": text,
        "start_seconds": start_seconds,
        "end_seconds": end_seconds,
        "duration_seconds": duration_seconds,
        "image_path": image_path,
        "audio_path": audio_path,
    }
    return result
